### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by homesomele** [chunbaobao/Deep-JSCC-PyTorch#7]
Hello, thank u so much for providing the codes of jscc pytorch, I found that the results are worse than the figure showed in the paper, can u restruct the same results as the paper?

**Comment by chunbaobao** [comment]
I found the same problem you mentioned. The models' performance is approximately 5dB worse than reported in the paper, as shown in the [README.md results](https://github.com/chunbaobao/Deep-JSCC-PyTorch#results). I believe this discrepancy is due to system differences: 

1. The complex communication system has twice as many parameters as the real-valued communication system implemented in the repository.
2. The noise power in the complex communication system is half that of the real-valued communication system.

**Comment by homesomele** [comment]
I found that after chaging the decoder transconv structure, the results are similar to the results showed in the paper 
![_GF%DI60(}336}CDO$HOSFK](https://github.com/chunbaobao/Deep-JSCC-PyTorch/assets/87977602/076178b6-b211-44e8-ad95-2a32e20817c7)

**Comment by chunbaobao** [comment]
Thanks for sharing. I noticed that you used the `output_padding` parameter with `kernel_size=5` in `tconv4-5`. However, I encountered a mismatch error when running your code pasted above. Could you please provide the whole modified code? Thanks in advance.

**Comment by homesomele** [comment]
Can u add my wechat if u are convinnient,  my wechat number is 18307784719, I can send it to u.
